### ISSUE TITLE
IP2Proxy-lite db with IP2Proxy==2.2.0 not working.

### ISSUE THREAD

**Issue by daniel-leicht** [ip2location/ip2proxy-python#1]
I tested with Google's ip (8.8.8.8) and with a known TOR exit node (109.169.33.163).
Both IPs are not showing any info in the country code and the is_proxy is always 0.

Tested on Python 3.6, installed the version from pypi.
I tried with the IP2PROXY binary databases of level 2 and level 5, same result.

Am I doing something wrong?

```
import IP2Proxy

db = IP2Proxy.IP2Proxy('IP2PROXY.BIN')


db.get_all("8.8.8.8") 
{'is_proxy': 0, 'proxy_type': '-', 'country_short': '-', 'country_long': '-', 'region': 'NOT SUPPORTED', 'city': 'NOT SUPPORTED', 'isp': 'NOT SUPPORTED', 'domain': 'NOT SUPPORTED', 'usage_type': 'NOT SUPPORTED', 'asn': 'NOT SUPPORTED', 'as_name': 'NOT SUPPORTED', 'last_seen': 'NOT SUPPORTED'}


db.get_all("109.169.33.163") 
{'is_proxy': 0, 'proxy_type': '-', 'country_short': '-', 'country_long': '-', 'region': 'NOT SUPPORTED', 'city': 'NOT SUPPORTED', 'isp': 'NOT SUPPORTED', 'domain': 'NOT SUPPORTED', 'usage_type': 'NOT SUPPORTED', 'asn': 'NOT SUPPORTED', 'as_name': 'NOT SUPPORTED', 'last_seen': 'NOT SUPPORTED'}
```

**Comment by ip2location** [comment]
Hi Daniel,

May I know how did you test the library? Are you testing directly in the interpreter in console, or are you testing using a script? If you are using a script, can you post the full source?

Also, which version of the IP2Proxy Lite Database that you had tried? We had tested with the latest version and no issue found.

**Comment by daniel-leicht** [comment]
Hi,

I contacted your support through the mail, it seems that the "country" fields are only shown if this is a positive proxy.

So this issue is not really a bug, thank you.
