### ISSUE TITLE
No results from IP2Proxy-lite databases

### ISSUE THREAD

**Issue by davidfischer** [ip2location/ip2proxy-python#2]
I'm not sure if this is related to #1 but I'm having issues with the IP2Proxy-lite databases. I tried a few different databases from https://lite.ip2location.com/file-download (PX1LITEBIN, PX10LITEBIN, etc.) but I didn't get any results for any known [Tor exit nodes](https://check.torproject.org/torbulkexitlist).

```python
import IP2Proxy
db = IP2Proxy.IP2Proxy()
db.open('IP2PROXY-LITE-PX10.BIN')
db.get_all("109.169.33.163") # {'is_proxy': 0, 'proxy_type': '-', 'country_short': '-', 'country_long': '-', 'region': '-', 'city': '-', 'isp': '-', 'domain': '-', 'usage_type': '-', 'asn': '-', 'as_name': '-', 'last_seen': '-'}
db.get_all("167.86.94.107")  # {'is_proxy': 0, 'proxy_type': '-', 'country_short': '-', 'country_long': '-', 'region': '-', 'city': '-', 'isp': '-', 'domain': '-', 'usage_type': '-', 'asn': '-', 'as_name': '-', 'last_seen': '-'}
db.get_all("199.249.230.82") # {'is_proxy': 0, 'proxy_type': '-', 'country_short': '-', 'country_long': '-', 'region': '-', 'city': '-', 'isp': '-', 'domain': '-', 'usage_type': '-', 'asn': '-', 'as_name': '-', 'last_seen': '-'}
print ('Module Version: ' + db.get_module_version()) # Module Version: 3.0.0
print ('Package Version: ' + db.get_package_version()) # Package Version: 10
print ('Database Version: ' + db.get_database_version()) # Database Version: 2020.7.1
```

I tried version 2.2.0 of the IP2Proxy python module but that didn't change the results. However, when I tried the sample DB [available here](https://ip2location.com/development-libraries#ip2proxy) I was able to get good results for the 3 IPs listed here. Is this just a matter of the limited accuracy of the lite databases or is there a larger issue with the library? I took a cursory look in the CSV versions of the databases and it looks like these exit nodes weren't present.

**Comment by ip2location** [comment]
Hi davidfischer,

TOR exit nodes are only available in the commercial database. The LITE databases did not contain any TOR exit nodes.

**Comment by davidfischer** [comment]
Thanks for the info. I'll close this one out.
