### ISSUE TITLE
Not detecting proxy

### ISSUE THREAD

**Issue by ostester1** [ip2location/ip2proxy-python#4]
I took the python code and BIN file (IP2Proxy PX10 Sample BIN File) from here:

https://www.ip2location.com/development-libraries/ip2proxy/python

It works fine. However, the sample files are 2 months old so I tried to download the July version of proxy BIN file from here:

https://lite.ip2location.com/database/px10-ip-proxytype-country-region-city-isp-domain-usagetype-asn-lastseen-threat-residential

Now for every proxy IP it says "not a proxy". For example, here is a Tor ip: 23.160.208.249

Here is the sample code:

```
# DOES NOT WORK WITH JULY BIN FILE
import IP2Proxy
IP_ADD = "192.95.39.118"
db = IP2Proxy.IP2Proxy()
### open IP2Proxy BIN database for proxy lookup
db.open("/Users/ostester1/Downloads/IP2PROXY-LITE-PX10.BIN/IP2PROXY-LITE-PX10.BIN")
### get versioning information
print ('Module Version: ' + db.get_module_version())
print ('Package Version: ' + db.get_package_version())
print ('Database Version: ' + db.get_database_version())
### single function to get all proxy data returned in array
record = db.get_all(IP_ADD)
print ('Is Proxy: ' + str(db.is_proxy(IP_ADD)))
### close IP2Proxy BIN database
db.close()
```

```
# WORKS GREAT WITH FOLLOWING BIN FILE
import IP2Proxy
IP_ADD = "192.95.39.118"
db = IP2Proxy.IP2Proxy()
### open IP2Proxy BIN database for proxy lookup
db.open("/Users/ostester1/Downloads/sample.bin.px10/IP2PROXY-IP-PROXYTYPE-COUNTRY-REGION-CITY-ISP-DOMAIN-USAGETYPE-ASN-LASTSEEN-THREAT-RESIDENTIAL.BIN")
### get versioning information
print ('Module Version: ' + db.get_module_version())
print ('Package Version: ' + db.get_package_version())
print ('Database Version: ' + db.get_database_version())
### single function to get all proxy data returned in array
record = db.get_all(IP_ADD)
print ('Is Proxy: ' + str(db.is_proxy(IP_ADD)))
### close IP2Proxy BIN database
db.close()
```

**Comment by ip2location** [comment]
Hi ostester1,

Please take note that for the LITE version of the IP2Proxy database, it do not contain full information of proxy IPs, for example the TOR IP addresses. So it is normal for some IP address to be return as "Not a proxy".

**Comment by ostester1** [comment]
@ip2location so how come for the same IP, sample file has it but not the free version for Lite proxy db?

**Comment by ip2location** [comment]
Hi ostester1,

The sample database is an outdated commercial database which consists of all proxy types.

The LITE database is a free database LIMITED to open proxy.

For IP address 103.255.5.116, it has been detected as residential proxy which is only available in commercial database. There is nothing wrong in the sample or LITE database.

For database issue, please contact IP2Location support via email directly. Github issues are suitable for library codes related support.
